### PR TITLE
Moves jam to cobra

### LINKED ISSUE #94: Add usage flags to jam commands/subcommands
## What happened?

When I run any `jam` command/subcommand without the expected flags I see output similar to the following:
```
jam
missing command%
...
jam pack
failed to execute: missing required flag --buildpack
```

It would be helpful if usage commands/flags are added to all jam commands/subcommands (e.g `jam --help`, `jam help`, `jam pack --help`, etc..)

### PR DESCRIPTION
**Pull request by emmjohnson**
## Summary

Moves jam to cobra for easier usage
Resolves #94 

## Checklist

* [x] I have viewed, signed, and submitted the Contributor License Agreement.
* [x] I have linked issue(s) that this PR should close using keywords or the Github UI (See [docs](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue))
* [x] I have added an integration test, if necessary.
* [x] I have reviewed the [styleguide](https://github.com/paketo-buildpacks/community/blob/main/STYLEGUIDE.md) for guidance on my code quality.

### CODE REVIEW

**Comment by ryanmoran** [comment]
Looks like a copy of the built `jam` executable got checked in. Can we remove that?

File: cargo/jam/commands/pack.go [hunk 1]
```diff
@@ -1,152 +1,104 @@
...
-		return err
-	}
-
-	if buildpackTOMLPath == "" {
-		return errors.New("missing required flag --buildpack")
+		fmt.Fprintf(os.Stderr, "Unable to mark buildpack flag as required")
 	}
-
-	if output == "" {
-		return errors.New("missing required flag --output")
```
Comment (sophiewigmore) [inline cargo/jam/commands/pack.go:103]: Is output not a required flag anymore? When I run `jam-darwin pack --buildpack <path> --version 1.2.3` with no `--output` flag, rather than giving me a nice output it returns:
```
Error: failed to create output: failed to create tarball: open : no such file or directory
```
Maybe this should return the `required flag(s) "output" not set` too

Comment (emmjohnson) [reply cargo/jam/commands/pack.go:103]: Good catch. We just need to add `cmd.MarkFlagRequired("output")`. I'm wondering why a unit test didn't catch this. Will look into.

Comment (emmjohnson) [reply cargo/jam/commands/pack.go:103]: Added a few more test cases and marked output as required.

File: cargo/jam/summarize_test.go [hunk 2]
```diff
@@ -431,4 +431,20 @@ version = "3.4.5"
 			}`))
 		})
 	})
+
+	context.Focus("failure cases", func() {
```
Comment (sophiewigmore) [inline cargo/jam/summarize_test.go:435]: Can you remove this focus?

Comment (emmjohnson) [reply cargo/jam/summarize_test.go]: This is why I shouldn't write code without a pair. Removed.

Comment (sophiewigmore) [reply cargo/jam/summarize_test.go]: LOL it's easy to miss

**Review by sophiewigmore — APPROVED** [review]
