### PR TITLE
Removes useage of OS specfic path separator

### LINKED ISSUE #185: Packit 0.12 fails on Windows
## What happened?
Using a tar.gz-based dependency when running in a Windows buildpack, `packit` incorrectly assumes the TAR file would use Windows path separators `\` ([example](https://github.com/paketo-buildpacks/packit/blob/5674dc46e9f2facabb06f6f3156e28ffb45e3421/vacation/vacation.go#L99)) instead of always using Unix path separators `/` as defined by the tar [spec](https://www.gnu.org/software/tar/manual/html_node/Standard.html#:~:text=separated%20by%20slashes).

Side note: all TARs use `/`, including Windows OCI image layers, only filesystem paths accessed in Windows runtime environments require `\` separators.

* What were you attempting to do?
Upgrade an unpublished, internal Windows buildpack from packit 0.8.0 to 0.12.0

* What did you expect to happen?
No-op upgrade

* What was the actual behavior? Please provide log output, if possible.
```
Downloading HWC
illegal file path "./": the file path does not occur within the destination directory
```

The dependency we're downloading is here:
```
curl --silent --location https://github.com/cloudfoundry/hwc/releases/download/20.0.0/hwc.tar.gz | tar tvz
drwxr-xr-x  0 root   root        0 Jun 26  2020 ./
-rwxr-xr-x  0 root   root  7058447 Jun 26  2020 ./hwc_x86.exe
-rwxr-xr-x  0 root   root  8579071 Jun 26  2020 ./hwc.exe
```

I assume this is because `packit` will normally ignore a `./` but since it assumes that it should be `.\` instead, it does not ignore it.

## Build Configuration

* What platform (`pack`, `kpack`, `tekton` buildpacks plugin, etc.) are you
  using? Please include a version.
pack @ `main`

* What buildpacks are you using? Please include versions.
Not publicly available.

* What builder are you using? If custom, can you provide the output from `pack
  inspect-builder <builder>`?

* Can you provide a sample app or relevant configuration (`buildpack.yml`,
  `nginx.conf`, etc.)?
```
...
[[metadata.dependencies]]
  id = "hwc"
  name = "Hosted Web Core"
  version = "20.0.0"
  uri = "https://github.com/cloudfoundry/hwc/releases/download/20.0.0/hwc.tar.gz"
  sha256 = "41d0859a1d553ce75dc65b34598dff4e0dd9ebd10750b52ec21f18394cb36800"
  stacks = ["io.buildpacks.stacks.windows.servercore"]
  source = "https://github.com/cloudfoundry/hwc/archive/20.0.0.tar.gz"
  source_sha256 = "643fd1225881bd6206eec205ba818cf60be00bd3a1029c86b0e5bf74a3a978ab"
...
```
## Checklist

* [x] I have included log output.
* [x] The log output includes an error message.
* [x] I have included steps for reproduction.

### PR DESCRIPTION
**Pull request by ForestEckhardt**
[TAR uses "/" regardless of the OS](https://www.gnu.org/software/tar/manual/html_node/Standard.html#:~:text=separated%20by%20slashes) therefore usage of "\" causes
incorrect behavior.

Resolves #185 

## Checklist

* [x] I have viewed, signed, and submitted the Contributor License Agreement.
* [x] I have linked issue(s) that this PR should close using keywords or the Github UI (See [docs](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue))
* [x] I have reviewed the [styleguide](https://github.com/paketo-buildpacks/community/blob/main/STYLEGUIDE.md) for guidance on my code quality.
* [x] I'm happy with the commit history on this PR (I have rebased/squashed as needed).

### CODE REVIEW

**Comment by ForestEckhardt** [comment]
@micahyoung If you wouldn't mind giving this branch a shot and see if it resolves everything for you that would be mighty helpful.

File: vacation/vacation.go [hunk 1]
```diff
@@ -479,7 +479,7 @@ func (z ZipArchive) Decompress(destination string) error {
 // directory
 func checkExtractPath(filePath string, destination string) error {
 	destpath := filepath.Join(destination, filePath)
-	if !strings.HasPrefix(destpath, filepath.Clean(destination)+string(os.PathSeparator)) {
+	if !strings.HasPrefix(destpath, filepath.Clean(destination)+"/") {
```
Comment (micahyoung) [inline vacation/vacation.go:482]: I needed one more change to get the comparison right:
```golang
func checkExtractPath(tarFilePath string, destination string) error {
	osPath := filepath.FromSlash(tarFilePath)
	destpath := filepath.Join(destination, osPath)
	if !strings.HasPrefix(destpath, filepath.Clean(destination)+string(os.PathSeparator)) {
		return fmt.Errorf("illegal file path %q: the file path does not occur within the destination directory", tarFilePath)
	}
	return nil
}
```	

Full commit (with yours as a parent) is here: https://github.com/micahyoung/packit/commit/869a1e0b98bc4a2b0dd23d3bdb4d2af3b9775f5a

Comment (ForestEckhardt) [reply vacation/vacation.go]: @micahyoung looks good to me! it has been added and is ready for testings.

**Review by micahyoung — APPROVED** [review]
This PR branch is all green on my buildpack! Thanks Forest!

**Review by sophiewigmore — APPROVED** [review]
